### ISSUE TITLE
Autocomplete fails in VS Code

### ISSUE THREAD

**Issue by selfagency** [pieces-app/support#362]
### Software

VS Code

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

```
Failed to provide autocomplete suggestions. Please ensure that Pieces OS is running and up-to-date. If the problem persists please reach out to support.
```

The extension host logs are full of this:

```
2024-08-14 18:18:45.975 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:45.975 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:45.975 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:49.763 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:49.763 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:49.763 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:49.763 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:49.763 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
2024-08-14 18:18:49.763 [error] FetchError: The request failed and the interceptors did not return an alternative response
    at Ty.IE.fetchApi (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170085)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ty.request (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:170714)
    at Ty.personsCreateNewPersonRaw (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424072)
    at Ty.personsCreateNewPerson (/Users/daniel/.vscode/extensions/meshintelligenttechnologiesinc.pieces-vscode-1.17.0/dist/extension.js:73:424250)
```

**Comment by caleb-at-pieces** [comment]
Hey @selfagency , thanks for letting me know about this. I'll take a look at this, I think it should be an easy fix. Will keep you posted!

**Comment by caleb-at-pieces** [comment]
Added an adjustment on how these errors are handled, thanks for reaching out!

**Comment by caleb-at-pieces** [comment]
Hello @johnkennyuk , the autocomplete within the VS Code extension is solely based on the snippets you have saved.

1. ensure you have some snippets saved
2. type something in your editor which directly matches the beginning of one of your snippets
3. you should see an inline completion option

**Comment by johnkennyuk** [comment]
So it doesn't use the llm api like copilot does, if it's only saved materials that's disappointing as I was assuming it would effectively be Pieces copilot but in line autocomplete using the same apis?
